import Foundation
import CoreFoundation

/// A `JapaneseAnalyzing` implementation backed by `CFStringTokenizer`.
///
/// Word-boundary tokenization is performed with `kCFStringTokenizerUnitWordBoundary`
/// and the `ja_JP` locale.  Readings are derived from
/// `kCFStringTokenizerAttributeLatinTranscription` + `kCFStringTransformLatinHiragana`.
/// Only tokens that contain at least one kanji receive a reading; purely kana / ASCII
/// tokens get `reading = nil`.
///
/// Known homographs (同形異音語) are flagged with `Reading.isUncertain = true` so the
/// UI can de-emphasize those glosses.
public struct StandardAnalyzer: JapaneseAnalyzing {

    // MARK: - Homograph table

    /// Surfaces that have multiple common readings.  Values are arbitrary (we just need
    /// membership); the reading is still generated by CFStringTokenizer.
    private static let homographs: Set<String> = [
        "日本", "明日", "今日", "一日", "市場",
        "行", "角", "生", "人", "上", "下",
        "何", "日", "中", "大", "小",
        "金", "白", "黒", "山"
    ]

    // MARK: - JapaneseAnalyzing

    public init() {}

    public func analyze(_ text: String) -> [AnalyzedToken] {
        guard !text.isEmpty else { return [] }

        let cfText = text as CFString
        let fullRange = CFRangeMake(0, CFStringGetLength(cfText))

        guard let tokenizer = CFStringTokenizerCreate(
            kCFAllocatorDefault,
            cfText,
            fullRange,
            kCFStringTokenizerUnitWordBoundary,
            Locale(identifier: "ja_JP") as CFLocale
        ) else { return [] }

        var tokens: [AnalyzedToken] = []

        while CFStringTokenizerAdvanceToNextToken(tokenizer) != [] {
            let cfRange = CFStringTokenizerGetCurrentTokenRange(tokenizer)

            // Convert CFRange (UTF-16 code-unit offsets) to Swift String.Index.
            guard
                let swiftRange = Range(cfRange, in: text)
            else { continue }

            let surface = String(text[swiftRange])

            let reading: Reading?
            if surface.containsKanji {
                reading = makeReading(for: surface, tokenizer: tokenizer)
            } else {
                reading = nil
            }

            tokens.append(AnalyzedToken(surface: surface, reading: reading, range: swiftRange))
        }

        return tokens
    }

    // MARK: - Private helpers

    /// Generate a `Reading` for `surface`, using the Latin transcription already
    /// available on the tokenizer's current position.
    private func makeReading(for surface: String, tokenizer: CFStringTokenizer) -> Reading? {
        // Retrieve the Latin (Romaji) transcription.
        guard let latinAttr = CFStringTokenizerCopyCurrentTokenAttribute(
            tokenizer,
            kCFStringTokenizerAttributeLatinTranscription
        ) as? String else { return nil }

        // Transform Latin → Hiragana.
        let mutable = NSMutableString(string: latinAttr)
        CFStringTransform(mutable, nil, kCFStringTransformLatinHiragana, false)
        let hiragana = mutable as String
        guard !hiragana.isEmpty else { return nil }

        let uncertain = Self.homographs.contains(surface)
        return Reading(hiragana: hiragana, isUncertain: uncertain)
    }
}

// MARK: - CFRange → Range<String.Index> bridge

private extension Range where Bound == String.Index {
    /// Convert a UTF-16-based `CFRange` to a `Range<String.Index>` within `string`.
    /// Returns `nil` if the offsets are out of bounds.
    init?(_ cfRange: CFRange, in string: String) {
        let utf16 = string.utf16
        guard
            cfRange.location != kCFNotFound,
            cfRange.location >= 0,
            cfRange.length >= 0
        else { return nil }

        let startOffset = cfRange.location
        let endOffset   = cfRange.location + cfRange.length

        guard
            startOffset <= utf16.count,
            endOffset   <= utf16.count
        else { return nil }

        let startIdx = utf16.index(utf16.startIndex, offsetBy: startOffset)
        let endIdx   = utf16.index(utf16.startIndex, offsetBy: endOffset)

        guard
            let swiftStart = startIdx.samePosition(in: string),
            let swiftEnd   = endIdx.samePosition(in: string)
        else { return nil }

        self = swiftStart ..< swiftEnd
    }
}
